name: Build Binaries
on: 
  push:
  workflow_call:

jobs:
  build:
      name: Build Binaries
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            path: minimega
        - name: Build
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential dnsmasq iproute2 isc-dhcp-client libpcap-dev ntfs-3g openssh-client openvswitch-switch qemu-kvm qemu-utils
            cd minimega
            ./scripts/all.bash
        # Only for release:
        - name: Tar
          if: github.event_name == 'workflow_dispatch'
          run: tar -czvf minimega-$( cat minimega/VERSION | cut -d'=' -f2 )-binaries.tar.gz minimega
        - name: Upload artifact
          uses: actions/upload-artifact@v4.0.0
          if: github.event_name == 'workflow_dispatch'
          with:
            name: minimega-binaries
            path: ./*.tar.gz
        - name: Upload python package
          uses: actions/upload-artifact@v4.0.0
          if: github.event_name == 'workflow_dispatch'
          with:
            name: minimega-python-dist
            path: ./lib/dist/