name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dh-systemd dnsmasq iproute2 isc-dhcp-client libpcap-dev ntfs-3g openssh-client openvswitch-switch qemu-kvm qemu-utils

    - name: Build Deb package
      id: deb
      run: |
        chmod +x ./packaging/debian/build.bash
        ./packaging/debian/build.bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: minimega-deb
        path: ./*.deb
